use strict;
use warnings;
use Test::More;
use File::Temp qw(tempdir);
use lib 'lib';
use App::Netdisco::Web::Plugin::AdminTask::Appearance::State;
my $dir = tempdir(CLEANUP => 1);
my $file = "$dir/appearance.json";
my $class = 'App::Netdisco::Web::Plugin::AdminTask::Appearance::State';
is $class->can('read_state')->($file), 0, 'missing state keeps current palette';
$class->can('write_state')->($file, 1);
is $class->can('read_state')->($file), 1, 'classic state survives a new read';
is((stat($file))[2] & 0777, 0600, 'saved state is private');
$class->can('write_state')->($file, 0);
is $class->can('read_state')->($file), 0, 'administrator can disable classic';
ok !eval { $class->can('write_state')->($file, 'invalid'); 1 }, 'rejects invalid writes';
is $class->can('read_state')->($file), 0, 'invalid write preserves previous state';
open my $fh, '>', $file or die $!;
print {$fh} '{"classic_colors":2}'; close $fh;
ok !eval { $class->can('read_state')->($file); 1 }, 'invalid persisted state is not accepted';
done_testing;
