version: 2
updates:
  - package-ecosystem: "uv"
    # Look for `package.json` and `lock` files here
    directory: "/share/python/netdisco/"
    schedule:
      interval: "daily"
    groups:
      python-dependencies:
        patterns:
          - "*"             # Bundles ALL python dependencies into one PR

  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"             # Bundles ALL GitHub Actions into one PR
