=head1 NAME

App::Netdisco::Manual::BSDInstall - BSD Install Instructions

=head1 Introduction

This document is compiled from suggestions and comments on the Netdisco mail
lists. We're grateful for the help, and if you have any additions please do
let the project staff know.

=head1 Ports Installs

=over 4

=item *

Perl (if not already installed)

=item *

C<p5-DBD-Pg> (will also pull in C<postgresqlXX-client>)

=item *

C<postgresqlXX-server>

=item *

C<net-snmp> (should install the Perl binding C<SNMP.pm>)

=back

=head1 Additional Steps

=head2 Netdisco User

 pw useradd netdisco -N -m -s /bin/sh -w no

=head2 PostgreSQL Setup

 /usr/local/etc/rc.d/postgresql initdb
 /usr/local/etc/rc.d/postgresql start

Make sure PostgreSQL starts at boot by adding the following to
"C</etc/rc.conf>":

 postgresql_enable="YES"

When installing C<postgresqlXX-server> port, it creates the C<pgsql> user with
"C<nologin>" shell. As root, do C<vipw> and change the shell to C</bin/sh> or
whichever shell you want, so that you can do the C<createuser> step from the
main instructions.

C<pgtune> doesn't seem to work on NetBSD. This needs looking into. Nothing
will break, but it just means the server probably isn't tuned to your system's
hardware (RAM, etc).

=head1 Run Control Script

 # PROVIDE: netdiscoweb
 # REQUIRE: DAEMON
 # BEFORE:  LOGIN
 # KEYWORD: shutdown
 
 rcvar="netdisco_enable"

See also L<https://www.freebsd.org/doc/en/books/porters-handbook/rc-scripts.html>

=cut
