name: Build and Publish Netdisco
on:
  workflow_dispatch:
    inputs:
      netdisco_docker_committish:
        description: 'netdisco-docker REF to use'
        required: false
        type: string
        default: 'master'
      run_tests:
        description: 'Run tests'
        required: false
        default:  'true'
      debug_tests:
        description: 'With build and test debug'
        required: false
        default:  'false'
      debug_containers:
        description: 'With container debug'
        required: false
        default:  'false'
      debug_dbdeploy:
        description: 'With db deploy debug'
        required: false
        default:  'false'
      debug_demo:
        description: 'With demo container debug'
        required: false
        default:  'false'

  push:
    branches:
      - master
    tags:
      - '2.[0-9][0-9][0-9][0-9][0-9][0-9]'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test_netdisco:
    name: Test and CPAN Upload
    if: |
      (github.event_name == 'workflow_dispatch' && github.event.inputs.run_tests == 'true')
      || (github.event_name != 'workflow_dispatch' && github.repository == 'netdisco/netdisco')
    runs-on: ubuntu-latest
    container:
      image: 'netdisco/netdisco:latest-backend'
      options: '--user root --entrypoint /bin/ash'
      volumes:
        - '/home/runner/work:/github/workspace'

    steps:
      - name: Install base packages
        run: apk add tmux bash curl sudo xz
      - name: Install other packages
        run: apk add openssh-client gcc make musl-dev musl-obstack-dev python3 perl-dev unzip
      - name: Install fake apt-get
        run: echo 'if [ "$1" == "update" ]; then exec apk update; else exec apk add openssh-client xz; fi' > /usr/local/bin/apt-get && chmod +x /usr/local/bin/apt-get

      - name: Add localhost
        run: echo "127.0.0.1 localhost" >> /etc/hosts

      - name: Check out latest code
        uses: actions/checkout@v6.0.2
        with:
          path: 'netdisco'
          ref: ${{ github.ref }}

      - name: Fix owner of checkout
        run: chown -R netdisco:netdisco ${GITHUB_WORKSPACE}/netdisco

      - name: Install Perl deps
        run: |
          sudo -u netdisco /home/netdisco/bin/localenv cpanm --notest Env::Path Test::Compile CPAN::Uploader Test::Pod
          sudo -u netdisco /home/netdisco/bin/localenv cpanm --notest --installdeps ${GITHUB_WORKSPACE}/netdisco

      - name: Run Tests
        id: build_and_run_tests
        run: |
          cd ${GITHUB_WORKSPACE}/netdisco
          sudo -u netdisco /home/netdisco/bin/localenv perl ./Build.PL
          sudo -u netdisco /home/netdisco/bin/localenv ./Build test --test_files xt/

      - name: Make release
        if: steps.build_and_run_tests.outcome == 'success'
        run: |
          cd ${GITHUB_WORKSPACE}/netdisco
          sudo -u netdisco /home/netdisco/bin/localenv rm ./MANIFEST
          sudo -u netdisco /home/netdisco/bin/localenv ./Build manifest
          sudo -u netdisco /home/netdisco/bin/localenv ./Build distmeta
          sudo -u netdisco /home/netdisco/bin/localenv ./Build dist

      - name: Upload to CPAN
        if: startsWith(github.ref, 'refs/tags/')
        env:
          PAUSE_USERNAME: ${{ secrets.PAUSE_USERNAME }}
          PAUSE_PASSWORD: ${{ secrets.PAUSE_PASSWORD }}
        run: |
          cd ${GITHUB_WORKSPACE}/netdisco
          bash -c 'RELEASENAME=(App-Netdisco-*.tar.gz) && ! curl -LI --fail https://cpan.metacpan.org/authors/id/O/OL/OLIVER/${RELEASENAME}'
          sudo -u netdisco /home/netdisco/bin/localenv cpan-upload -u '${{ env.PAUSE_USERNAME }}' -p '${{ env.PAUSE_PASSWORD }}' App-Netdisco-*.tar.gz

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3.23
        if: always() && github.event.inputs.debug_tests == 'true'
        with:
          sudo: true

  build_containers:
    name: Build Container Images
    needs: test_netdisco
    if: |
      always() && 
      !cancelled() && 
      !failure() &&
      (needs.test_netdisco.result == 'success' || needs.test_netdisco.result == 'skipped') &&
      (github.event_name == 'workflow_dispatch') || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:3
        ports: ["5000:5000"]

    steps:
      - name: Check out latest dockerfiles
        uses: actions/checkout@v6.0.2
        with:
          repository: 'netdisco/netdisco-docker'
          path: 'netdisco-docker'
          ref: ${{ ((github.event.inputs.netdisco_docker_committish != '') && github.event.inputs.netdisco_docker_committish) || 'master' }}

      - name: Get the Tag
        run: |
          echo "COMMITTISH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
          echo "IMAGE_ROOT=netdisco:$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Set up Docker
        uses: docker/setup-docker-action@v5.2.0
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.1.0
        with:
          driver-opts: |
            network=host
            default-load=false

      - name: Build images with Bake and Cache
        uses: docker/bake-action@v7.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMITTISH: ${{ env.COMMITTISH }}
        with:
          source: /home/runner/work/netdisco/netdisco/netdisco-docker
          files: docker-bake.hcl
          targets: all
          push: true
          set: |
            *.platform=linux/amd64,linux/arm64
            *.args.BUILD_DATE=${{ env.BUILD_DATE }}
            *.args.COMMITTISH=${{ env.COMMITTISH }}
            netdisco-web.cache-from=type=gha,scope=netdisco-backend-global
            netdisco-web.cache-from=type=gha,scope=netdisco-web-global
            netdisco-web.cache-to=type=gha,mode=max,scope=netdisco-web-global-${{ github.run_id }}-${{ github.run_attempt }}
            netdisco-backend.cache-from=type=gha,scope=netdisco-web-global
            netdisco-backend.cache-from=type=gha,scope=netdisco-backend-global
            netdisco-backend.cache-to=type=gha,mode=max,scope=netdisco-backend-global-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Install skopeo
        run: sudo apt-get update && sudo apt-get install -y skopeo

      - name: Login to DH
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo '${{ env.DOCKER_PASSWORD }}' | docker login -u '${{ env.DOCKER_USERNAME }}' --password-stdin

      - name: Upload to Docker Hub
        id: upload_docker_hub
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          for image in postgresql postgresql-13 backend web; do
            skopeo copy --src-tls-verify=false --all docker://localhost:5000/netdisco:${COMMITTISH}-$image docker://docker.io/netdisco/netdisco:${COMMITTISH}-$image
            skopeo copy --src-tls-verify=false --all docker://localhost:5000/netdisco:${COMMITTISH}-$image docker://docker.io/netdisco/netdisco:latest-$image
          done

      - name: Logout from DH
        run: docker logout

      - name: Login to GHP
        run: |
          echo '${{ secrets.GITHUB_TOKEN }}' | docker login ghcr.io -u '${{ github.actor }}' --password-stdin

      - name: Upload to GitHub Packages
        id: upload_github_packages
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          for image in postgresql postgresql-13 backend web; do
            skopeo copy --src-tls-verify=false --all docker://localhost:5000/netdisco:${COMMITTISH}-$image docker://ghcr.io/netdisco/netdisco:${COMMITTISH}-$image
            skopeo copy --src-tls-verify=false --all docker://localhost:5000/netdisco:${COMMITTISH}-$image docker://ghcr.io/netdisco/netdisco:latest-$image
          done

      - name: Logout from GHP
        run: docker logout

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3.23
        if: always() && github.event.inputs.debug_containers == 'true'
        with:
          sudo: true

  redeploy_demo_db:
    name: Redeploy Demo DB
    needs: build_containers
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    container:
      image: 'netdisco/netdisco:latest-backend'
      options: '--user root --entrypoint /bin/ash'
      volumes:
        - '/home/runner/work:/github/workspace'

    steps:
      - name: Install packages
        run: apk add curl gzip sudo

      - name: Add IP address as trusted source (managed database)
        uses: rachelallyson/add-ip-to-digital-ocean-database@v1.0
        with:
          action: "add"
          database_id: ${{ secrets.DIGITALOCEAN_DEMO_DB_ID }}
          digitalocean_token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Download db content
        run: |
          cd ${GITHUB_WORKSPACE}
          curl -LO https://raw.githubusercontent.com/netdisco/netdisco2-demo/refs/heads/master/netdisco2-demo-cumulus-clean.db.sql
          curl -LO https://raw.githubusercontent.com/netdisco/upstream-sources/refs/heads/master/bootstrap/netdisco-lookup-tables.sql
          curl -LO https://raw.githubusercontent.com/netdisco/netdisco2-demo/refs/heads/master/netdisco2-demo-snmp-object-data.sql.gz
          gunzip netdisco2-demo-snmp-object-data.sql.gz

      - name: Upload cumulus demo
        env:
          PGUSER:     ${{ secrets.DIGITALOCEAN_DEMO_DB_USER }}
          PGPASSWORD: ${{ secrets.DIGITALOCEAN_DEMO_DB_PASS }}
          PGHOST:     ${{ secrets.DIGITALOCEAN_DEMO_DB_HOST }}
          PGPORT:     ${{ secrets.DIGITALOCEAN_DEMO_DB_PORT }}
          PGDATABASE: ${{ secrets.DIGITALOCEAN_DEMO_DB_NAME }}
        run: |
          cd ${GITHUB_WORKSPACE}
          psql -c "DROP OWNED BY $PGUSER CASCADE"
          psql -X -v ON_ERROR_STOP=0 -v ON_ERROR_ROLLBACK=on -d ${{ env.PGDATABASE }} -f netdisco2-demo-cumulus-clean.db.sql

      - name: Update schema
        env:
          NETDISCO_HOME: /github/workspace/netdisco/netdisco
          NETDISCO_DB_USER: ${{ secrets.DIGITALOCEAN_DEMO_DB_USER }}
          NETDISCO_DB_PASS: ${{ secrets.DIGITALOCEAN_DEMO_DB_PASS }}
          NETDISCO_DB_HOST: ${{ secrets.DIGITALOCEAN_DEMO_DB_HOST }}
          NETDISCO_DB_PORT: ${{ secrets.DIGITALOCEAN_DEMO_DB_PORT }}
          NETDISCO_DB_NAME: ${{ secrets.DIGITALOCEAN_DEMO_DB_NAME }}
        run: |
          /home/netdisco/bin/localenv /home/netdisco/bin/netdisco-db-deploy

      - name: Upload IANA/IEEE tables
        env:
          PGUSER:     ${{ secrets.DIGITALOCEAN_DEMO_DB_USER }}
          PGPASSWORD: ${{ secrets.DIGITALOCEAN_DEMO_DB_PASS }}
          PGHOST:     ${{ secrets.DIGITALOCEAN_DEMO_DB_HOST }}
          PGPORT:     ${{ secrets.DIGITALOCEAN_DEMO_DB_PORT }}
          PGDATABASE: ${{ secrets.DIGITALOCEAN_DEMO_DB_NAME }}
        run: |
          cd ${GITHUB_WORKSPACE}
          psql -X -v ON_ERROR_STOP=0 -v ON_ERROR_ROLLBACK=on -d ${{ env.PGDATABASE }} -f netdisco-lookup-tables.sql

      - name: Upload SNMP Objects and Analze all tables
        env:
          PGUSER:     ${{ secrets.DIGITALOCEAN_DEMO_DB_USER }}
          PGPASSWORD: ${{ secrets.DIGITALOCEAN_DEMO_DB_PASS }}
          PGHOST:     ${{ secrets.DIGITALOCEAN_DEMO_DB_HOST }}
          PGPORT:     ${{ secrets.DIGITALOCEAN_DEMO_DB_PORT }}
          PGDATABASE: ${{ secrets.DIGITALOCEAN_DEMO_DB_NAME }}
        run: |
          cd ${GITHUB_WORKSPACE}
          psql -X -v ON_ERROR_STOP=0 -v ON_ERROR_ROLLBACK=on -d ${{ env.PGDATABASE }} -f netdisco2-demo-snmp-object-data.sql
          psql -c "VACUUM ANALYZE"

      - name: Update statistics
        env:
          NETDISCO_HOME: /github/workspace/netdisco/netdisco
          NETDISCO_DB_USER: ${{ secrets.DIGITALOCEAN_DEMO_DB_USER }}
          NETDISCO_DB_PASS: ${{ secrets.DIGITALOCEAN_DEMO_DB_PASS }}
          NETDISCO_DB_HOST: ${{ secrets.DIGITALOCEAN_DEMO_DB_HOST }}
          NETDISCO_DB_PORT: ${{ secrets.DIGITALOCEAN_DEMO_DB_PORT }}
          NETDISCO_DB_NAME: ${{ secrets.DIGITALOCEAN_DEMO_DB_NAME }}
        run: |
          rm /tmp/uv* && /home/netdisco/bin/localenv /home/netdisco/bin/netdisco-do stats -D

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3.23
        if: always() && github.event.inputs.debug_dbdeploy == 'true'
        with:
          sudo: true

      - name: Remove IP address as trusted source (managed database)
        uses: rachelallyson/add-ip-to-digital-ocean-database@v1.0
        with:
          action: "remove"
          database_id: ${{ secrets.DIGITALOCEAN_DEMO_DB_ID }}
          digitalocean_token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

  build_demo_container:
    name: Build Demo Container
    needs: redeploy_demo_db
    runs-on: ubuntu-latest

    steps:
      - name: Check out latest dockerfile
        uses: actions/checkout@v6.0.2
        with:
          repository: 'netdisco/netdisco2-demo'
          path: 'netdisco2-demo'
          ref: 'master'

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build netdisco-demo container image
        run: |
          cd ${GITHUB_WORKSPACE}/netdisco2-demo/docker
          docker build --tag registry.digitalocean.com/netdisco-demo-webonly/demo:latest .

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/netdisco-demo-webonly/demo:latest

      - name: Logout from DigitalOcean
        run: docker logout

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3.23
        if: always() && github.event.inputs.debug_demo == 'true'
        with:
          sudo: true
